<Workspace Version="1.0.1.1821" X="-4.36904761904702" Y="115.952380952381" zoom="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="6adae558-1d83-4903-a231-a2cf88d4567c" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="81" y="14" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="1b788b58-e0bf-484d-9743-fd8172265c3b-0000b9cf" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementSelection guid="7ce00e02-b10b-4b31-b93c-bad204a56499" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="82.75" y="107.95" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="1b788b58-e0bf-484d-9743-fd8172265c3b-0000b968" />
    </Dynamo.Nodes.DSModelElementSelection>
    <CoreNodeModels.CreateList guid="8fb17c16-f942-4e1f-b7d2-e69935c70da6" type="CoreNodeModels.CreateList" nickname="Create List" x="257.95" y="47.35" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="265d3748-0dce-4abb-8564-a281c8eba453" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.End" x="641.826176494656" y="72.9722865974853" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.End@var" />
    <PythonNodeModels.PythonNode guid="1a1d3ed8-9649-41ce-b8c0-d85072ae38fb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="460.501162790698" y="61.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#derived from Nathan Miller's example http://theprovingground.wikidot.com/revit-api-py-curves

# Default imports
import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
import Autodesk
import sys
import clr
path = r'C:\Autodesk\Dynamo\Core'
exec_path = r'C:\Users\Ian\Documents\GitHub\Dynamo\bin\AnyCPU\Debug'
sys.path.append(path)
sys.path.append(exec_path)
clr.AddReference('LibGNet')
from Autodesk.LibG import *
import math

doc = __revit__.ActiveUIDocument.Document
app = __revit__.Application

# get the input points
beginPoint = IN[0][0]
endPoint = IN[0][1]

# The __persistent__ dictionary gives you a persistent
# dictionary between runs.  Here we use it to store elements
# we wish to clean up later.

# Initialize if it's not already created.
if 'oldElements' not in __persistent__:
	__persistent__['oldElements'] = []

#delete old elements
if __persistent__['oldElements'].Count &gt; 0:
     count = 0
     for eID in __persistent__['oldElements']:
          doc.Delete( __persistent__['oldElements'][count] )
          count = count + 1

# Clear the dictionary as we've deleted those old elements
__persistent__['oldElements'] = []

lineRefPointArray = ReferencePointArray()
lineRefPointArray.Append(beginPoint)
lineRefPointArray.Append(endPoint)

crv = doc.FamilyCreate.NewCurveByPoints(lineRefPointArray)
crvRef = crv.GeometryCurve
refptarr = ReferencePointArray()

#use for loop to create a series of points
steps = 20
for i in range(0,steps+1):
    pt = crvRef.Evaluate(float(i)/steps,1) # returns and XYZ
    x = pt.X
    y = pt.Y
    z = pt.Z + math.sin(i)*steps 
    myXYZ = XYZ(x,y,z)
    refPt = doc.FamilyCreate.NewReferencePoint(myXYZ)
    __persistent__['oldElements'].Add(refPt.Id)
    refptarr.Append(refPt)
</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="211fc774-26a9-4c0a-8445-959fbee9ffd8" type="CoreNodeModels.Watch" nickname="Watch" x="742.369047619047" y="232.247619047619" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6adae558-1d83-4903-a231-a2cf88d4567c" start_index="0" end="8fb17c16-f942-4e1f-b7d2-e69935c70da6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7ce00e02-b10b-4b31-b93c-bad204a56499" start_index="0" end="8fb17c16-f942-4e1f-b7d2-e69935c70da6" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8fb17c16-f942-4e1f-b7d2-e69935c70da6" start_index="0" end="1a1d3ed8-9649-41ce-b8c0-d85072ae38fb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1a1d3ed8-9649-41ce-b8c0-d85072ae38fb" start_index="0" end="265d3748-0dce-4abb-8564-a281c8eba453" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1a1d3ed8-9649-41ce-b8c0-d85072ae38fb" start_index="0" end="211fc774-26a9-4c0a-8445-959fbee9ffd8" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="d243c7f0-9ba5-4966-848d-0fb4363c3d17" text="Create a transaction to wrap the python script." x="576.833333333333" y="12.4166666666666" />
    <Dynamo.Graph.Notes.NoteModel guid="c73440f5-5ef3-49dd-85c0-b4bffca40efa" text="Select two points." x="84" y="200" />
    <Dynamo.Graph.Notes.NoteModel guid="401972b7-658b-468b-ac21-ffe389335dfe" text="Create a list." x="282" y="147" />
    <Dynamo.Graph.Notes.NoteModel guid="03dba840-289a-47e1-8d77-4ba3941ccdba" text="Make a python script." x="456" y="139" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>