<Workspace Version="1.0.1.1821" X="76.6309523809526" Y="104.952380952381" zoom="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7d934c8e-f5ff-43b6-b224-7fe968dbe9aa" type="PythonNodeModels.PythonNode" nickname="Python Script" x="212.901162790698" y="38.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#derived from Nathan Miller's example http://theprovingground.wikidot.com/revit-api-py-curves
# Default imports
import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
import Autodesk
import sys
import clr
path = r'C:\Autodesk\Dynamo\Core'
exec_path = r'C:\Users\Ian\Documents\GitHub\Dynamo\bin\AnyCPU\Debug'
sys.path.append(path)
sys.path.append(exec_path)
clr.AddReference('LibGNet')
from Autodesk.LibG import *
import math

doc = __revit__.ActiveUIDocument.Document
app = __revit__.Application

crv = IN[0]
crvRef = crv.GeometryCurve
refptarr = ReferencePointArray()

#use for loop to create a series of points
steps = 20
for i in range(0,steps+1):
    pt = crvRef.Evaluate(float(i)/steps,1) # returns and XYZ
    x = pt.X
    y = pt.Y
    z = pt.Z + math.sin(i)*steps 
    myXYZ = XYZ(x,y,z)
    refPt = doc.FamilyCreate.NewReferencePoint(myXYZ)
    refptarr.Append(refPt)
crv2 = doc.FamilyCreate.NewCurveByPoints(refptarr)
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="052930f8-51c7-4db1-ae80-5e2b20cbf752" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="c85d11af-8f27-41a9-b135-16103b79fdab-0000ba7b" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b11ed0cc-5e1c-4b17-a921-602a9b30ca1f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.End" x="390.40026896506" y="54.3213830149307" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.End@var" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7d934c8e-f5ff-43b6-b224-7fe968dbe9aa" start_index="0" end="b11ed0cc-5e1c-4b17-a921-602a9b30ca1f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="052930f8-51c7-4db1-ae80-5e2b20cbf752" start_index="0" end="7d934c8e-f5ff-43b6-b224-7fe968dbe9aa" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>