<Workspace Version="1.0.1.1821" X="285.659722119934" Y="33.8949282085639" zoom="0.565293988808902" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e2f3ee81-e1f8-4fc0-85d2-0d35ab675b2b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ModelCurve.ByCurve" x="677.5" y="410.5" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9daf8dcd-0f4f-42f4-bad0-0fdfb0b75aee" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Plane.ByOriginNormal" x="324.75" y="413.75" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c8e3f161-b793-44c8-a7b3-bcbb21093925" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.AsVector" x="174.75" y="513.75" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.AsVector" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e13297a0-d297-4a3b-8440-a34ba4d4331e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="SketchPlane.ByPlane" x="465" y="427" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.SketchPlane.ByPlane@Autodesk.DesignScript.Geometry.Plane" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d58f9a13-4d72-4dc7-9b1b-707de865afb0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="204.25" y="503.75" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double" />
    <CoreNodeModels.Input.DoubleInput guid="e400dcaa-91e3-438f-9527-d22adb802cb7" type="CoreNodeModels.Input.DoubleInput" nickname="Number" x="27.25" y="543.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double value="0" />
    </CoreNodeModels.Input.DoubleInput>
    <CoreNodeModels.Input.DoubleSlider guid="14ff78f4-1bb6-45a8-b229-18a4aef94494" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="0" y="411.25" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>0</System.Double>
      <Range min="0" max="100" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <CoreNodeModels.Input.DoubleSlider guid="4a65b7d1-b17a-4afc-a25c-cafa87e1422e" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="194" y="612.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>30.909</System.Double>
      <Range min="0" max="200" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <Watch3DNodeModels.Watch3D guid="35f32e64-b677-4be8-9886-f139b9c4a091" type="Watch3DNodeModels.Watch3D" nickname="Watch 3D" x="712.923076923077" y="36" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <view width="210" height="257">
        <Camera Name="35f32e64-b677-4be8-9886-f139b9c4a091 Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
        <Camera Name="35f32e64-b677-4be8-9886-f139b9c4a091 Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
      </view>
    </Watch3DNodeModels.Watch3D>
    <CoreNodeModels.CreateList guid="9c74f383-9e66-4599-a320-d2a095b0cebf" type="CoreNodeModels.CreateList" nickname="Create List" x="398.173076923077" y="157.25" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="112d99f0-1637-4d0f-81f0-9bf43ff595da" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CurveElement.Curve" x="262.5" y="118.75" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6e5bcf5f-355a-48a5-8728-d0a800818835" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Ellipse.ByOriginRadii" x="518.5" y="514.25" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Ellipse.ByOriginRadii@Autodesk.DesignScript.Geometry.Point,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.DoubleSlider guid="ddba3f8b-dc83-4cdc-982b-371081acc2f5" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="191.25" y="691.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>200</System.Double>
      <Range min="0" max="200" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="253c5f85-1dce-4374-abfd-df96022c0974" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.AsPoint" x="195.664622606165" y="287.508415718876" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.AsPoint" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e0183056-2981-40db-be68-ad17a84f7b39" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.ZAxis" x="45.664622606165" y="287.508415718876" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ZAxis" />
    <Dynamo.Nodes.DSModelElementSelection guid="f49df017-5696-4220-bd29-d8e34bd38751" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="0" y="130.083318923715" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="c85d11af-8f27-41a9-b135-16103b79fdab-0000ba7b" />
    </Dynamo.Nodes.DSModelElementSelection>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9daf8dcd-0f4f-42f4-bad0-0fdfb0b75aee" start_index="0" end="e13297a0-d297-4a3b-8440-a34ba4d4331e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c8e3f161-b793-44c8-a7b3-bcbb21093925" start_index="0" end="9daf8dcd-0f4f-42f4-bad0-0fdfb0b75aee" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d58f9a13-4d72-4dc7-9b1b-707de865afb0" start_index="0" end="9daf8dcd-0f4f-42f4-bad0-0fdfb0b75aee" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d58f9a13-4d72-4dc7-9b1b-707de865afb0" start_index="0" end="6e5bcf5f-355a-48a5-8728-d0a800818835" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e400dcaa-91e3-438f-9527-d22adb802cb7" start_index="0" end="d58f9a13-4d72-4dc7-9b1b-707de865afb0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e400dcaa-91e3-438f-9527-d22adb802cb7" start_index="0" end="d58f9a13-4d72-4dc7-9b1b-707de865afb0" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="14ff78f4-1bb6-45a8-b229-18a4aef94494" start_index="0" end="d58f9a13-4d72-4dc7-9b1b-707de865afb0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a65b7d1-b17a-4afc-a25c-cafa87e1422e" start_index="0" end="6e5bcf5f-355a-48a5-8728-d0a800818835" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9c74f383-9e66-4599-a320-d2a095b0cebf" start_index="0" end="35f32e64-b677-4be8-9886-f139b9c4a091" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="112d99f0-1637-4d0f-81f0-9bf43ff595da" start_index="0" end="9c74f383-9e66-4599-a320-d2a095b0cebf" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6e5bcf5f-355a-48a5-8728-d0a800818835" start_index="0" end="9c74f383-9e66-4599-a320-d2a095b0cebf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6e5bcf5f-355a-48a5-8728-d0a800818835" start_index="0" end="e2f3ee81-e1f8-4fc0-85d2-0d35ab675b2b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ddba3f8b-dc83-4cdc-982b-371081acc2f5" start_index="0" end="6e5bcf5f-355a-48a5-8728-d0a800818835" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="253c5f85-1dce-4374-abfd-df96022c0974" start_index="0" end="c8e3f161-b793-44c8-a7b3-bcbb21093925" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e0183056-2981-40db-be68-ad17a84f7b39" start_index="0" end="253c5f85-1dce-4374-abfd-df96022c0974" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f49df017-5696-4220-bd29-d8e34bd38751" start_index="0" end="112d99f0-1637-4d0f-81f0-9bf43ff595da" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>