<Workspace Version="0.9.0.2777" X="-839.189339908715" Y="-380.348494189323" zoom="1.51939327724693" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="9a42b0b5-e39e-49d7-9b5b-6ee9cb930eb9" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="666.597119149974" y="284.066600001573" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="a=Point.Origin();&#xA;b=Point.ByCoordinates(0.00065104,0,0);&#xA;Line.ByStartPointEndPoint(a,b);" ShouldFocus="false" />
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="0.084832988679409" eyeY="0.894189238548279" eyeZ="0.906177759170532" lookX="2.94613671302795" lookY="-5.78939151763916" lookZ="-6.40849208831787" upX="0.189631149172783" upY="0.891006529331207" upZ="-0.412489265203476" />
  </Cameras>
</Workspace>