<?xml version="1.0"?>
<migrations>
  <priorNameHint>
    <oldName>Revit.Elements.AdaptiveComponent.Symbol</oldName>
    <newName>Revit.Elements.AdaptiveComponent.Type</newName>
  </priorNameHint>
   <priorNameHint>
    <oldName>Revit.Elements.Family.Symbols</oldName>
    <newName>Revit.Elements.Family.Types</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.FamilyInstance.Symbol</oldName>
    <newName>Revit.Elements.FamilyInstance.Type</newName>
  </priorNameHint>
   <priorNameHint>
    <oldName>Revit.Elements.FamilyInstance.ByFamilySymbol</oldName>
    <newName>Revit.Elements.FamilyInstance.ByFamilyType</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.FamilySymbol</oldName>
    <newName>Revit.Elements.FamilyType</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.FamilySymbol.ByFamilyAndName</oldName>
    <newName>Revit.Elements.FamilyType.ByFamilyAndName</newName>
  </priorNameHint>
    <priorNameHint>
    <oldName>Revit.Elements.FamilySymbol.ByFamilyNameAndTypeName</oldName>
    <newName>Revit.Elements.FamilyType.ByFamilyNameAndTypeName</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.FamilySymbol.ByName</oldName>
    <newName>Revit.Elements.FamilyType.ByName</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.FamilySymbol.Name</oldName>
    <newName>Revit.Elements.FamilyType.Name</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.FamilySymbol.Family</oldName>
    <newName>Revit.Elements.FamilyType.Family</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.StructuralFraming.Symbol</oldName>
    <newName>Revit.Elements.StructuralFraming.Type</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.AdaptiveComponent.ByPoints@Autodesk.DesignScript.Geometry.Point[],Revit.Elements.FamilySymbol</oldName>
    <newName>Revit.Elements.AdaptiveComponent.ByPoints@Autodesk.DesignScript.Geometry.Point[][],Revit.Elements.FamilySymbol</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.AdaptiveComponent.ByParametersOnFace@Autodesk.DesignScript.Geometry.UV[],Autodesk.DesignScript.Geometry.Surface,Revit.Elements.FamilySymbol</oldName>
    <newName>Revit.Elements.AdaptiveComponent.ByParametersOnFace@Autodesk.DesignScript.Geometry.UV[][],Autodesk.DesignScript.Geometry.Surface,Revit.Elements.FamilySymbol</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Revit.Elements.AdaptiveComponent.ByParametersOnCurveReference@double[],Autodesk.DesignScript.Geometry.Curve,Revit.Elements.FamilySymbol</oldName>
    <newName>Revit.Elements.AdaptiveComponent.ByParametersOnCurveReference@double[][],Autodesk.DesignScript.Geometry.Curve,Revit.Elements.FamilySymbol</newName>
  </priorNameHint>
</migrations>
