<Workspace Version="0.8.0.950" X="184.163321671989" Y="152.100250855786" zoom="0.771968318564611" Name="Home" RunType="Manual" RunPeriod="100" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="ff9d94a0-07d1-4d08-92fa-a8e36363c5eb" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-28.7327667414587" y="505.778192976719" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="100;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="d999bf5b-0106-4da5-b026-709223216971" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-28.7327667414587" y="666.428055096386" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="200;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="fcc76b3a-58b3-48af-a631-1286885596a7" type="Dynamo.Nodes.DSFunction" nickname="Plane.Offset" x="399.990300090683" y="212.213594004749" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Plane.Offset@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction guid="e9ad31dd-d8be-4b5e-9408-11ffa76b09bb" type="Dynamo.Nodes.DSFunction" nickname="Plane.XY" x="-28.7327667414587" y="212.213594004749" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Plane.XY" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="8675705b-5aa5-4fac-83c5-954b18a0f610" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-28.7327667414587" y="359.058297107209" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="80;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="c8ce0012-5862-4706-9947-0724cd223d1d" type="Dynamo.Nodes.DSFunction" nickname="Rectangle.ByWidthHeight" x="606.74486618893" y="466.338821248007" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Rectangle.ByWidthHeight@Autodesk.DesignScript.Geometry.Plane,double,double">
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction guid="c0a52a3e-0565-4884-a063-ebe7140e868d" type="Dynamo.Nodes.DSFunction" nickname="Rectangle.ByWidthHeight" x="606.74486618893" y="251.420999943833" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Rectangle.ByWidthHeight@Autodesk.DesignScript.Geometry.Plane,double,double">
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction guid="d67bb390-bb4c-4713-8736-758cb784f395" type="Dynamo.Nodes.DSFunction" nickname="Polygon.Points" x="833.515362445942" y="251.775425501079" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Polygon.Points" />
    <Dynamo.Nodes.DSFunction guid="635ea1d1-d27c-457f-aa3e-7d9d680cb384" type="Dynamo.Nodes.DSFunction" nickname="Polygon.Points" x="833.515362445942" y="440.679797363174" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Polygon.Points" />
    <Dynamo.Nodes.DSFunction guid="14719205-f9d8-40a0-9a04-2760c5c816be" type="Dynamo.Nodes.DSFunction" nickname="Flatten" x="1220.97145796864" y="334.662745094003" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="" function="Flatten@var[]..[]" />
    <DSCoreNodesUI.CreateList guid="0056d458-29f6-433d-b1c8-12e7ab68c1f6" type="DSCoreNodesUI.CreateList" nickname="List.Create" x="1057.90276503453" y="333.210104316745" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="2" />
    <Dynamo.Nodes.DSFunction guid="700fd421-636c-4cd9-8604-36f027f045ee" type="Dynamo.Nodes.DSFunction" nickname="AdaptiveComponent.ByPoints" x="1472.52511049747" y="335.564023988199" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.AdaptiveComponent.ByPoints@Autodesk.DesignScript.Geometry.Point[],Revit.Elements.FamilySymbol" />
    <DSRevitNodesUI.FamilyTypes guid="d38ebf32-028f-4643-87ad-d62c8813d507" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="613.955773384149" y="705.508191376328" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="10:BLDG-COMPONENT-STRUCTURE-FULLYADAPTIVE:BLDG-COMPONENT-STRUCTURE-FULLYADAPTIVE" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="ff9d94a0-07d1-4d08-92fa-a8e36363c5eb" start_index="0" end="c8ce0012-5862-4706-9947-0724cd223d1d" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="ff9d94a0-07d1-4d08-92fa-a8e36363c5eb" start_index="0" end="c0a52a3e-0565-4884-a063-ebe7140e868d" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="d999bf5b-0106-4da5-b026-709223216971" start_index="0" end="c8ce0012-5862-4706-9947-0724cd223d1d" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="d999bf5b-0106-4da5-b026-709223216971" start_index="0" end="c0a52a3e-0565-4884-a063-ebe7140e868d" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="fcc76b3a-58b3-48af-a631-1286885596a7" start_index="0" end="c0a52a3e-0565-4884-a063-ebe7140e868d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e9ad31dd-d8be-4b5e-9408-11ffa76b09bb" start_index="0" end="fcc76b3a-58b3-48af-a631-1286885596a7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e9ad31dd-d8be-4b5e-9408-11ffa76b09bb" start_index="0" end="c8ce0012-5862-4706-9947-0724cd223d1d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8675705b-5aa5-4fac-83c5-954b18a0f610" start_index="0" end="fcc76b3a-58b3-48af-a631-1286885596a7" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="c8ce0012-5862-4706-9947-0724cd223d1d" start_index="0" end="635ea1d1-d27c-457f-aa3e-7d9d680cb384" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c0a52a3e-0565-4884-a063-ebe7140e868d" start_index="0" end="d67bb390-bb4c-4713-8736-758cb784f395" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d67bb390-bb4c-4713-8736-758cb784f395" start_index="0" end="0056d458-29f6-433d-b1c8-12e7ab68c1f6" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="635ea1d1-d27c-457f-aa3e-7d9d680cb384" start_index="0" end="0056d458-29f6-433d-b1c8-12e7ab68c1f6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="14719205-f9d8-40a0-9a04-2760c5c816be" start_index="0" end="700fd421-636c-4cd9-8604-36f027f045ee" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="0056d458-29f6-433d-b1c8-12e7ab68c1f6" start_index="0" end="14719205-f9d8-40a0-9a04-2760c5c816be" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d38ebf32-028f-4643-87ad-d62c8813d507" start_index="0" end="700fd421-636c-4cd9-8604-36f027f045ee" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Origin Plane" x="-28.7327667414587" y="170.097062526047" />
    <Dynamo.Models.NoteModel text="Height" x="-28.7327667414587" y="323.544576692258" />
    <Dynamo.Models.NoteModel text="Width" x="-28.7327667414587" y="464.996078607567" />
    <Dynamo.Models.NoteModel text="Length" x="-28.7327667414587" y="622.184732160624" />
    <Dynamo.Models.NoteModel text="Offset Plane for Roof Level" x="399.990300090683" y="167.832218673274" />
    <Dynamo.Models.NoteModel text="Create Roof Rectangle" x="607.021534427831" y="206.318688288265" />
    <Dynamo.Models.NoteModel text="Create Ground Rectangle" x="609.28917869736" y="420.918691727165" />
    <Dynamo.Models.NoteModel text="Extract points from rectangle." x="835.742121454141" y="398.910170161368" />
    <Dynamo.Models.NoteModel text="Extract points from rectangle." x="832.177824669802" y="207.706434527017" />
    <Dynamo.Models.NoteModel text="Merge lists and flatten, in order with Adaptive Component setup." x="1058.07621515385" y="273.093979729732" />
    <Dynamo.Models.NoteModel text="Create Adaptive component from points." x="1471.7057055684" y="289.509425207422" />
    <Dynamo.Models.NoteModel text="Select Family Type to create adaptive component." x="614.840496931239" y="654.168039391516" />
    <Dynamo.Models.NoteModel text="Note: Notice in the bottom left of the interface, the &quot;Manual&quot; option is checked.  Since we are generating Revit elements, the solver will be slow with each run.  Now that we're in 'Manual' mode, remember to hit the 'Run' button to see an update." x="-30.1481738768336" y="-1.48216736358131" />
  </Notes>
</Workspace>