<Workspace Version="1.0.1.1821" X="-0.249999999999943" Y="-62.3333333333333" zoom="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="25456637-2521-4245-900a-2272c4df3581" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.ByPoint" x="584.485989150352" y="164.707893063616" isVisible="true" isUpstreamVisible="true" lacing="First" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByPoint@Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b435825a-40eb-4c0a-964b-6b5aed4a3d5d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="425.385267964278" y="181.960591131775" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double" />
    <CoreNodeModels.Input.DoubleInput guid="24aa71f1-a184-4b28-a992-753ada5d1030" type="CoreNodeModels.Input.DoubleInput" nickname="Number" x="227.457136532039" y="223.147374698933" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double value="0" />
    </CoreNodeModels.Input.DoubleInput>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b435825a-40eb-4c0a-964b-6b5aed4a3d5d" start_index="0" end="25456637-2521-4245-900a-2272c4df3581" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="24aa71f1-a184-4b28-a992-753ada5d1030" start_index="0" end="b435825a-40eb-4c0a-964b-6b5aed4a3d5d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="24aa71f1-a184-4b28-a992-753ada5d1030" start_index="0" end="b435825a-40eb-4c0a-964b-6b5aed4a3d5d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="24aa71f1-a184-4b28-a992-753ada5d1030" start_index="0" end="b435825a-40eb-4c0a-964b-6b5aed4a3d5d" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>