<Workspace Version="1.0.1.1821" X="120.169736115557" Y="-537.44847590464" zoom="0.954042924882813" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="84a1ec5e-c906-4f90-a351-7b87683d8eff" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.TrimByParameter" x="531.869120520432" y="975.369303777039" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.TrimByParameter@double,double" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ff304620-d3cd-4f91-9f66-9a18abc2b343" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.ParameterAtPoint" x="381.869120520432" y="975.369303777039" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.ParameterAtPoint@Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5812e36b-423f-4b62-ba11-e1e96a6757d1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.ParameterAtPoint" x="381.869120520432" y="1075.36930377704" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.ParameterAtPoint@Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d025f3be-7410-451f-ac1f-1f2972663fa2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CurveByPoints.ByReferencePoints" x="531.869120520432" y="1139.93212994053" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.CurveByPoints.ByReferencePoints@Revit.Elements.ReferencePoint[],bool">
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="534ad6a2-7804-4ec4-a2a6-80be06f71d2b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ModelCurve.ByCurve" x="881.958190193084" y="833.866236693782" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6491777a-f3d7-4509-b01a-8e6d1868c7fa" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ModelCurve.ReferenceCurveByCurve" x="881.958190193084" y="1058.17480229243" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ModelCurve.ReferenceCurveByCurve@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cdca4311-81b0-4c66-a4a3-8cabaeb7795e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CurveElement.Curve" x="531.869120520432" y="720.663783027175" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <Dynamo.Nodes.ModelCurveNurbSpline type="Dynamo.Nodes.ModelCurveNurbSpline" guid="43b07208-01e4-4145-a052-123ce6ca9119" nickname="Nurbs Spline Model Curve" x="531.869120520432" y="850.636970570316" isVisible="true" isUpstreamVisible="true" lacing="Longest">
      <Run />
    </Dynamo.Nodes.ModelCurveNurbSpline>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9f0be9e5-9703-4c21-a843-18faa55313de" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.XYPlane" x="881.958190193084" y="721.711953894459" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.XYPlane" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5e17f7a8-28aa-41bb-8028-1b79becd86d5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ModelCurve.ReferenceCurveByCurve" x="881.958190193084" y="1170.32908509175" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ModelCurve.ReferenceCurveByCurve@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="004047d2-a263-4979-b84e-8cce83b6db99" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.ByPoint" x="881.958190193084" y="946.020519493104" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByPoint@Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5ec89d04-403d-4917-8525-6ebd536a50a3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.ByLengthOnCurveReference" x="266.681891097734" y="721.711953894459" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByLengthOnCurveReference@var,double" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0bd651e3-7198-48fc-ab13-e4ce30a503e2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="116.681891097734" y="721.711953894459" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="// Convert ModelCurve into CurveReference&#xA;curve.CurveReference;&#xA;&#xA;// Convert normalized length into actual length&#xA;// and flip the evaluation if 'beginning' is set to false&#xA;len * (normalized ? curve.Curve.Length : 1)&#xA;* (beginning ? 1 : -1) + (beginning ? 0 : curve.Curve.Length);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b388a76d-3d92-4ce8-9ffb-b6ee844e3001" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.ByPointVectorDistance" x="266.681891097734" y="895.708317863502" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByPointVectorDistance@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,double" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="96cfcf1d-dde2-4ac8-be78-d8375551957e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.Point" x="116.681891097734" y="895.708317863502" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.Point" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="aff4c98c-27de-4e00-a6bb-d931580e24a8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.AsVector" x="116.681891097734" y="995.708317863502" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.AsVector" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a7f80f82-ddd6-48f7-989e-efd29bb1a009" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.Normalized" x="116.681891097734" y="1095.7083178635" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.Normalized" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7cfdeb7b-6ff8-4419-b94b-ee284f01d792" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.ByParameterOnCurveReference" x="266.681891097734" y="1047.69309361959" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByParameterOnCurveReference@var,double" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6d09b42c-2c46-4fa3-a224-79f27e4877ad" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.ByPoint" x="266.681891097734" y="1171.37725595903" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByPoint@Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e05ae721-3d6f-4427-91e4-0bf050c1cc8a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.PointAtParameter" x="116.681891097734" y="1171.37725595903" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="674be8fa-88e7-4c78-b3fb-a18a94331820" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="UV.U" x="116.681891097734" y="1271.37725595903" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.UV.U" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c3945f1f-2c15-4bd0-9e0f-6ce1eef8197c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="UV.V" x="116.681891097734" y="1371.37725595903" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.UV.V" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ff304620-d3cd-4f91-9f66-9a18abc2b343" start_index="0" end="84a1ec5e-c906-4f90-a351-7b87683d8eff" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5812e36b-423f-4b62-ba11-e1e96a6757d1" start_index="0" end="84a1ec5e-c906-4f90-a351-7b87683d8eff" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0bd651e3-7198-48fc-ab13-e4ce30a503e2" start_index="0" end="5ec89d04-403d-4917-8525-6ebd536a50a3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0bd651e3-7198-48fc-ab13-e4ce30a503e2" start_index="1" end="5ec89d04-403d-4917-8525-6ebd536a50a3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96cfcf1d-dde2-4ac8-be78-d8375551957e" start_index="0" end="b388a76d-3d92-4ce8-9ffb-b6ee844e3001" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aff4c98c-27de-4e00-a6bb-d931580e24a8" start_index="0" end="a7f80f82-ddd6-48f7-989e-efd29bb1a009" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a7f80f82-ddd6-48f7-989e-efd29bb1a009" start_index="0" end="b388a76d-3d92-4ce8-9ffb-b6ee844e3001" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e05ae721-3d6f-4427-91e4-0bf050c1cc8a" start_index="0" end="6d09b42c-2c46-4fa3-a224-79f27e4877ad" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="674be8fa-88e7-4c78-b3fb-a18a94331820" start_index="0" end="e05ae721-3d6f-4427-91e4-0bf050c1cc8a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c3945f1f-2c15-4bd0-9e0f-6ce1eef8197c" start_index="0" end="e05ae721-3d6f-4427-91e4-0bf050c1cc8a" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>