<Workspace Version="1.0.1.1821" X="-205.305029622496" Y="-214.729805362915" zoom="0.627408126597635" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="5a31e807-b164-4d10-aac2-2a1b4c681a37" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="BoundingBoxXYZ" x="501.73590504451" y="716.059347181009" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="1e10c22b-18f6-452c-8220-4b1407c80b7b" />
      <Name value="BoundingBoxXYZ" />
      <Description value="This node represents an upgrade of the 0.6.3 BoundingBoxXYZ node to 0.7.x" />
      <Inputs>
        <Input value="coordinate system" />
        <Input value="width" />
        <Input value="length" />
        <Input value="height" />
      </Inputs>
      <Outputs>
        <Output value="bounding box" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1841b589-95b4-4f7d-afb2-caf3b377b4f7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Length" x="501.73590504451" y="865.218595450049" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Length" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8cc77bfe-51ac-407d-bb19-688f14c0a3b8" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Get Curve Domain" x="501.73590504451" y="1014.37784371909" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{0,1};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="778ba4a2-9e79-4d00-a185-75296a726705" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Get Surface Domain" x="501.73590504451" y="1163.53709198813" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{{0,0},{1,1}};" ShouldFocus="false" />
    <Dynamo.Nodes.Height type="Dynamo.Nodes.Height" guid="016677a4-9581-416f-a663-2f96720d460d" nickname="Height" x="881.557863501484" y="1163.53709198813" isVisible="true" isUpstreamVisible="true" lacing="Longest" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="adddc640-e339-4e05-8e7d-02149bdc1840" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.DistanceTo" x="881.557863501484" y="1014.37784371909" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.DistanceTo@Autodesk.DesignScript.Geometry.Geometry" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5aaafec0-9ec8-4313-9f4e-97ff6aa1cb22" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.Point" x="731.557863501484" y="1014.37784371909" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.Point" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="55150e2e-8849-41cf-83c9-16e82bf36fed" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePoint.Point" x="731.557863501484" y="1114.37784371909" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePoint.Point" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="51912527-90b7-4830-8fe5-61b1c8d5a642" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Volume" x="881.557863501484" y="865.218595450049" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Volume" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8401d843-4686-4206-88ad-0c04cef6a41f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.Area" x="881.557863501484" y="716.059347181009" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.Area" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5aaafec0-9ec8-4313-9f4e-97ff6aa1cb22" start_index="0" end="adddc640-e339-4e05-8e7d-02149bdc1840" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="55150e2e-8849-41cf-83c9-16e82bf36fed" start_index="0" end="adddc640-e339-4e05-8e7d-02149bdc1840" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>