<Workspace Version="1.0.1.1830" X="250.436301755381" Y="-26.8367067608211" zoom="0.252194253773829" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7b60d3f8-de71-4bb4-a5dc-0b3000de8f97" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="AxonometricView.ByEyePointAndTarget" x="611.530106433969" y="736.386346036426" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Views.AxonometricView.ByEyePointAndTarget@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,string">
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="67683f16-6695-4221-ae48-20b22e35d1f1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="DraftingView.ByName" x="611.530106433969" y="935.53881082027" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Views.DraftingView.ByName@string" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="34d9ee8c-3ea3-41d6-ba82-379588710f2e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.ActiveView" x="611.530106433969" y="1053.98211882329" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.ActiveView" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e9b5177b-cd6c-4856-8801-ecace51425f1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.OverrideColorInView" x="258.296524159467" y="1130.49859213498" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.OverrideColorInView@DSCore.Color" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1d014806-dcfc-40fc-a582-6bf2f4982f96" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PerspectiveView.ByEyePointAndTarget" x="258.296524159467" y="929.24978561657" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Views.PerspectiveView.ByEyePointAndTarget@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,var,string,bool" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ded91363-f8a8-42fb-bd7a-914d865ef3eb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="View.ExportAsImage" x="258.296524159467" y="1260.47177967812" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Views.View.ExportAsImage@string" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9a67b962-74bf-439c-94e5-c0ff1ee08983" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="SectionView.ByBoundingBox" x="611.530106433969" y="1155.65469294978" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Views.SectionView.ByBoundingBox@Autodesk.DesignScript.Geometry.BoundingBox" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ecbc8b84-fb3a-4375-84d7-3352773f95ff" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Sheet.ByNameNumberTitleBlockAndViews" x="258.296524159467" y="736.386346036426" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Views.Sheet.ByNameNumberTitleBlockAndViews@string,string,Revit.Elements.FamilyType,Revit.Elements.Views.View[]" />
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>