<Workspace Version="1.0.1.1821" X="84.8364620076049" Y="-279.816301402738" zoom="0.627408126597635" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="405a0450-8bbd-4f4e-8a9e-a67052a7a84e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Floor.ByOutlineTypeAndLevel" x="760.370369588211" y="897.804659598068" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Floor.ByOutlineTypeAndLevel@Autodesk.DesignScript.Geometry.Curve[],Revit.Elements.FloorType,Revit.Elements.Level" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1c182b6f-3118-43f3-8db4-1d3af2a37978" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Material.ByName" x="760.370369588211" y="1070.75285269983" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Material.ByName@string" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="cab4f898-2850-4e42-b625-2754769bb94e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Get Parameters" x="760.370369588211" y="1208.06323631395" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="element;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="126c3588-aac7-485f-aa73-00b4b6cc01ed" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Topography.Points" x="442.774596801343" y="1216.44860325222" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Topography.Points" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3c1fe69f-7c63-4ad6-9c27-655db0edaa91" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.Current" x="442.774596801343" y="1075.99370703624" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.Current" />
    <DSRevitNodesUI.FloorTypes guid="83e42dd8-6adf-43ab-86ea-5e0767481a0d" type="DSRevitNodesUI.FloorTypes" nickname="Floor Types" x="760.370369588211" y="762.590617718511" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:No floor types available." />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5d9e5759-8b05-48fc-99c1-309575f9c426" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Topography.ByPoints" x="442.774596801343" y="950.213202962238" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Topography.ByPoints@Autodesk.DesignScript.Geometry.Point[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="17694e70-768e-426b-88d5-5c666cc03b64" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Wall.ByCurveAndHeight" x="442.774596801343" y="760.494275983944" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Wall.ByCurveAndHeight@Autodesk.DesignScript.Geometry.Curve,double,Revit.Elements.Level,Revit.Elements.WallType" />
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>