<Workspace Version="1.0.1.1830" X="-197.517951340105" Y="-701.611406400634" zoom="0.716982951558227" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="CoordinateSystem" resolvedName="Autodesk.DesignScript.Geometry.CoordinateSystem" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cylinder" resolvedName="Autodesk.DesignScript.Geometry.Cylinder" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="30b81abb-90b7-4b18-93c6-739982783079" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Difference" x="795.908341538873" y="1077.67718568398" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Difference@Autodesk.DesignScript.Geometry.Solid" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="edfd2034-86b8-4a50-9ef6-6143dfb16bc6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Intersect" x="795.908341538873" y="927.986201427379" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Intersect@Autodesk.DesignScript.Geometry.Geometry" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a7ea69b0-4ddf-49d7-97ea-563d725eb0ae" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Union" x="795.908341538873" y="778.295217170775" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Union@Autodesk.DesignScript.Geometry.Solid" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c6537369-5c75-492c-9730-a8bde094f75e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Union" x="795.908341538873" y="1377.05915419719" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Union@Autodesk.DesignScript.Geometry.Solid" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="741f8aa9-3637-4494-a093-eb59d64de28b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.ByLoft" x="386.358787938683" y="1072.07544406939" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[]" />
    <CoreNodeModels.CreateList guid="70c715b4-b099-4d61-8f72-d6ffc3207d2d" type="CoreNodeModels.CreateList" nickname="Create List" x="236.358787938683" y="1072.07544406939" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="953dadc0-fe61-4563-b6f9-f07a216df3a0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.ExtrudeAsSolid" x="386.358787938683" y="1359.63151361846" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid@Autodesk.DesignScript.Geometry.Vector,double" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="54315bd4-5bc6-4f39-8185-162f5bbc5366" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.AsVector" x="236.358787938683" y="1459.63151361846" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.AsVector" />
    <Dynamo.Nodes.CreateRevolvedGeometry type="Dynamo.Nodes.CreateRevolvedGeometry" guid="258914ff-a39e-49b4-a0fd-c6124c8a22da" nickname="Revolve" x="386.358787938683" y="1190.33443371078" isVisible="true" isUpstreamVisible="true" lacing="Longest" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7b4345ae-2c49-4774-afb5-457fa6ded867" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Autodesk.DesignScript.Geometry.Solid.BySweep" x="386.358787938683" y="912.737015920989" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.BySweep@Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6f076124-8919-40eb-ab61-73e06ab3a66c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Autodesk.DesignScript.Geometry.Solid.BySweep" x="386.358787938683" y="774.560722761047" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.BySweep@Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="bfe0183a-fbb5-44c0-bbda-f17baf54c997" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Explode" x="795.908341538873" y="1227.36816994059" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Explode" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7bb57fcf-c942-4e90-b3f9-4162be5dab48" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Solids" x="386.358787938683" y="1516.48027882704" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Solids" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="91a64cab-046a-4410-97c9-4577abb56a1d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Cuboid.ByLengths" x="0.461032266772008" y="769.581396881409" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Cuboid.ByLengths@Autodesk.DesignScript.Geometry.Point,double,double,double">
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f02f10bf-7352-416b-8593-ec6334191da2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-149.538967733228" y="769.581396881409" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.ByCoordinates(0,0,0);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="81c66124-7548-4627-b68d-665b4af7f536" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Cuboid.ByCorners" x="0.461032266772008" y="1411.91443535466" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Cuboid.ByCorners@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="664d11c2-4463-4e2a-9499-3d6a44fd675b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-149.538967733228" y="1411.91443535466" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.ByCoordinates(-1,-1,-1);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f423745f-8823-4bc3-ba5c-df51bacf54d6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-149.538967733228" y="1511.91443535466" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.ByCoordinates(1,1,1);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="1207002e-8906-4e71-afc9-f82d092c7eba" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="0.461032266772008" y="932.65431943954" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="p=Plane.ByOriginNormal(origin,axis.AsVector());&#xA;cs=CoordinateSystem.ByPlane(p);&#xA;Cylinder.ByRadiusHeight(cs,r,h);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0e851bcc-5ebe-497d-bcc4-c69b7512280e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Sphere.ByCenterPointRadius" x="0.461032266772008" y="1113.1548825764" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="07f5bdbd-4e50-4558-8eb2-f8908e9ea1da" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-149.538967733228" y="1113.1548825764" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.ByCoordinates(0,0,0);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="70c715b4-b099-4d61-8f72-d6ffc3207d2d" start_index="0" end="741f8aa9-3637-4494-a093-eb59d64de28b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54315bd4-5bc6-4f39-8185-162f5bbc5366" start_index="0" end="953dadc0-fe61-4563-b6f9-f07a216df3a0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f02f10bf-7352-416b-8593-ec6334191da2" start_index="0" end="91a64cab-046a-4410-97c9-4577abb56a1d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="664d11c2-4463-4e2a-9499-3d6a44fd675b" start_index="0" end="81c66124-7548-4627-b68d-665b4af7f536" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f423745f-8823-4bc3-ba5c-df51bacf54d6" start_index="0" end="81c66124-7548-4627-b68d-665b4af7f536" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="07f5bdbd-4e50-4558-8eb2-f8908e9ea1da" start_index="0" end="0e851bcc-5ebe-497d-bcc4-c69b7512280e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>