{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "CreateWallInDynamo",
  "ElementResolver": {
    "ResolutionMap": {
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "b568d298f7be461999a1cae16efaed58",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "8c566d3b054049f8bc5548ca5eb2209a",
          "Name": "curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a42122054e8d4a568cb6bd29087a89c9",
          "Name": "height",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb50fe6cad4342acb88d97d9f5b64968",
          "Name": "level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "feb95dd297ef4a95bdbbf4d946195828",
          "Name": "wallType",
          "Description": "WallType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7a57c9133b1b4e8d9020c42a2d91b0b6",
          "Name": "Wall",
          "Description": "Wall",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Revit.Elements.Wall.ByCurveAndHeight@Autodesk.DesignScript.Geometry.Curve,double,Revit.Elements.Level,Revit.Elements.WallType",
      "Replication": "Auto",
      "Description": "Create a Revit Wall from a guiding Curve, height, Level, and WallType\n\nWall.ByCurveAndHeight (curve: Curve, height: double, level: Level, wallType: WallType): Wall"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "2087a05098b142828eae45bd8718ec3d",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "85e70fee411a4ec8b36ce8245095afe8",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b42bd06d68204286b1679a626f17708b",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "35a688186fb44063ac813430d254467f",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "76fde6505a614852ab36f563762b4aec",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "c81af38f9e004050bf97dbc1f08d4425",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0fb703be9d05456aa7825fd207859e9f",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7ef5946d9dbc4ef8893a612ad12f7154",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "89caad7b4fc2434e8919f8af1ae53b2a",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "Point.ByCoordinates(0,0,0);\nPoint.ByCoordinates(30,0,0);\n10;\n0;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "96964feced6c48409d8c8c35bb121b60",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "bd6aec57dbc74cb997717baec45f03e5",
          "Name": "elevation",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "13889d7b494b4f2696bc9b27cd5a2f34",
          "Name": "Level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Revit.Elements.Level.ByElevation@double",
      "Replication": "Auto",
      "Description": "Create a Revit Level given it's elevation. The name will be whatever Revit gives it.\n\nLevel.ByElevation (elevation: double): Level"
    },
    {
      "ConcreteType": "DSRevitNodesUI.WallTypes, DSRevitNodesUI",
      "SelectedIndex": 10,
      "SelectedString": "Generic - 12\"",
      "Id": "8de442024867400080ff3e28dc53056f",
      "NodeType": "ExtensionNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1a05d968b80043e8a97c8f465f48733e",
          "Name": "Wall Type",
          "Description": "The selected Wall Type",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "All wall types available in the document."
    }
  ],
  "Connectors": [
    {
      "Start": "35a688186fb44063ac813430d254467f",
      "End": "8c566d3b054049f8bc5548ca5eb2209a",
      "Id": "00890b54bf6b41639deee8f53c1acfaf",
      "IsHidden": "False"
    },
    {
      "Start": "c81af38f9e004050bf97dbc1f08d4425",
      "End": "85e70fee411a4ec8b36ce8245095afe8",
      "Id": "a021b6389d014187b49efc0fa970dbb6",
      "IsHidden": "False"
    },
    {
      "Start": "0fb703be9d05456aa7825fd207859e9f",
      "End": "b42bd06d68204286b1679a626f17708b",
      "Id": "202491b0e8004a49821a0297838bf335",
      "IsHidden": "False"
    },
    {
      "Start": "7ef5946d9dbc4ef8893a612ad12f7154",
      "End": "a42122054e8d4a568cb6bd29087a89c9",
      "Id": "1f02b0b486cf455b83d72e4ee2334d48",
      "IsHidden": "False"
    },
    {
      "Start": "89caad7b4fc2434e8919f8af1ae53b2a",
      "End": "bd6aec57dbc74cb997717baec45f03e5",
      "Id": "91ddff78aad54ce0ad1e2764dddc7616",
      "IsHidden": "False"
    },
    {
      "Start": "13889d7b494b4f2696bc9b27cd5a2f34",
      "End": "fb50fe6cad4342acb88d97d9f5b64968",
      "Id": "5f3f0fc214e54c538cafa063c2c6d78d",
      "IsHidden": "False"
    },
    {
      "Start": "1a05d968b80043e8a97c8f465f48733e",
      "End": "feb95dd297ef4a95bdbbf4d946195828",
      "Id": "76199941cd7e4ba089912b2dfe43addd",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "EnableLegacyPolyCurveBehavior": null,
  "Thumbnail": null,
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "3.0",
      "Data": {}
    },
    {
      "ExtensionGuid": "DFBD9CC0-DB40-457A-939E-8C8555555A9D",
      "Name": "Generative Design",
      "Version": "7.0",
      "Data": {}
    }
  ],
  "Author": "None provided",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [
    {
      "NodeId": "b568d298-f7be-4619-99a1-cae16efaed58",
      "Binding": {
        "ByCurveAndHeight_InClassDecl-1_InFunctionScope-1_Instance0_b568d298-f7be-4619-99a1-cae16efaed58": "H4sIAAAAAAAACh3LoQ6AIBAG4Hf5s7fBiYBmi9noGQ5BZzE4mvPd3fz6tzzIWhUDHsFc7/M6plEwCFzbq/eho5K8JWdzpn4vOzlljluXXI5MxpiWk6qgEUxX/S+bEKJ/8a4f2TQ+xF4AAAA="
      }
    },
    {
      "NodeId": "96964fec-ed6c-4840-9d8c-8c35bb121b60",
      "Binding": {
        "ByElevation_InClassDecl-1_InFunctionScope-1_Instance0_96964fec-ed6c-4840-9d8c-8c35bb121b60": "H4sIAAAAAAAACh3LvQqDMBAA4He52YN45te5S5YuHXsOFxNLwYZS4iS+e8X1g++5Q5YmMMLOEOt3a3f5FIaxbuvaMTza711f8XYKgx6CWOsMlmR71H3OGJayoBYiP5uksydUSg2UJDCcPdZ2XVLOeXPAMf0BzDtMK3EAAAA="
      }
    }
  ],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "3.0.0.5795",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "b568d298f7be461999a1cae16efaed58",
        "Name": "Wall.ByCurveAndHeight",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 556.5,
        "Y": 234.0
      },
      {
        "Id": "2087a05098b142828eae45bd8718ec3d",
        "Name": "Line.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 301.5,
        "Y": 107.0
      },
      {
        "Id": "76fde6505a614852ab36f563762b4aec",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 15.0,
        "Y": 194.0
      },
      {
        "Id": "96964feced6c48409d8c8c35bb121b60",
        "Name": "Level.ByElevation",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 330.5,
        "Y": 319.0
      },
      {
        "Id": "8de442024867400080ff3e28dc53056f",
        "Name": "Wall Types",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 240.5,
        "Y": 459.0
      }
    ],
    "Annotations": [],
    "X": 0.0,
    "Y": 0.0,
    "Zoom": 1.0
  }
}