{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "RebindingSingleDimension",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "16aa986904a94577889ce8b99114eaa5",
      "NodeType": "CodeBlockNode",
      "Inputs": [
        {
          "Id": "2c9548b98e21499bbf416bb7f3605487",
          "Name": "end",
          "Description": "end",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a4f8fed927424a7988d7eae3c968e776",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "Autodesk.Point.ByCoordinates(0..end, 0,0);"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NumberType": "Double",
      "Id": "8d9300ea8f8a4c2cb010a26e3f00ff6d",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "efc97ab564244acbb1274c988cc8b4ac",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number",
      "InputValue": 5.0
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "9af28bf1e5ea419a95c8d4932f503377",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "78f887e5048e4515bf2f6ea38a59f115",
          "Name": "pt",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "113f9cbeaeea49b3a91258b633f766d9",
          "Name": "ReferencePoint",
          "Description": "ReferencePoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Revit.Elements.ReferencePoint.ByPoint@Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Create a Reference Point from a point.\n\nReferencePoint.ByPoint (pt: Point): ReferencePoint"
    }
  ],
  "Connectors": [
    {
      "Start": "a4f8fed927424a7988d7eae3c968e776",
      "End": "78f887e5048e4515bf2f6ea38a59f115",
      "Id": "0d75a20e7d8240678c810f36f1dab844",
      "IsHidden": "False"
    },
    {
      "Start": "efc97ab564244acbb1274c988cc8b4ac",
      "End": "2c9548b98e21499bbf416bb7f3605487",
      "Id": "f3d22f6102854ac5800e32441753c1d1",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "EnableLegacyPolyCurveBehavior": null,
  "Thumbnail": null,
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "3.0",
      "Data": {}
    }
  ],
  "Author": "None provided",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [
    {
      "NodeId": "9af28bf1-e5ea-419a-95c8-d4932f503377",
      "Binding": {
        "ByPoint_InClassDecl-1_InFunctionScope-1_Instance0_9af28bf1-e5ea-419a-95c8-d4932f503377": "H4sIAAAAAAAACq3MqxLDIBCF4XdZHWZ2KdfomOjKEAGBdGoQLY7h3ZuJLJajfnO+rUJO35Li4ouHeasQ74Dq4Fk+7/xaFwezAy1IB8Mt4yg4E4F7FhIhO4M00gubFHqG1/SBh4PJwZrL/X2QlqpBm4bYsbP1MDt1thlmn51tR9mE/7bCYTZ1Nl323vYfHTw4XzoCAAA="
      }
    }
  ],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "3.0.0.5795",
      "RunType": "Manual",
      "RunPeriod": "100"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "16aa986904a94577889ce8b99114eaa5",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 169.0,
        "Y": 4.21833333333331
      },
      {
        "Id": "8d9300ea8f8a4c2cb010a26e3f00ff6d",
        "Name": "Number",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "Id": "9af28bf1e5ea419a95c8d4932f503377",
        "Name": "ReferencePoint.ByPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 687.0,
        "Y": 0.0
      }
    ],
    "Annotations": [],
    "X": 130.097546502025,
    "Y": 351.643411740913,
    "Zoom": 0.906217674817656
  }
}